Merge feature branch in main
nventive/Chinook.DynamicMvvm pull request #74
Opened 2022-09-28 16:29 UTC by GabrielChouinardLetourneau

GitHub Issue: #

## Proposed Changes

 - [ ] Bug fix
 - [ ] Feature
 - [ ] Code style update (formatting)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build or CI related changes
 - [ ] Documentation content changes
 - [ ] Other, please describe:

## What is the current behavior?

## What is the new behavior?

## Impact on version

- [ ] **Major** (Public API was modified.)
  - Public constructs (class, struct, delegate, enum, etc.) were removed or renamed.
  - Public members were removed or renamed.
  - Public method signatures were changed or renamed.
- [ ] **Minor** (Public API was extended.)
  - Public constructs, members, or overloads were added.
- [ ] **Patch** (Public API was unchanged.)
  - A bug in behavior was fixed.
  - Documentation was changed.
- [ ] **None** (The library is unchanged.)
  - Only code under the `build` folder was changed.
  - Only code under the `.github` folder was changed.

## Checklist

Please check that your PR fulfills the following requirements:

- [ ] Documentation has been added/updated.
- [ ] Automated Unit / Integration tests for the changes have been added/updated.
- [ ] Updated [BREAKING_CHANGES.md](../BREAKING_CHANGES.md) (if you introduced a breaking change).
- [ ] Your conventional commits are aligned with the **Impact on version** section.

## Other information

2022-09-28 16:36 UTC, carlh98 requested changes

2022-09-28 16:36 UTC, carlh98 commented on build/stage-build.yml
> +    arguments: 'install android ios'
Add other workload

2022-09-28 16:36 UTC, carlh98 commented on src/DynamicMvvm.Uno.WinUI/DynamicMvvm.Uno.WinUI.csproj
> +		<TargetFrameworks>net6.0-windows10.0.18362;netstandard2.0;net6.0-android;net6.0-ios;</TargetFrameworks>
add missing workload

2022-09-29 00:49 UTC, carlh98 commented on src/DynamicMvvm.Uno.WinUI/DynamicMvvm.Uno.WinUI.csproj
> +		<PackageReference Include="MSBuild.Sdk.Extras" Version="3.0.44" />
you can remove msbuild package from here

2022-09-29 15:40 UTC, lamonfly commented on build/stage-build.yml
>    inputs:
There shouldn't be a need to authenticate for NuGet packages.

2022-09-30 17:04 UTC, jeanplevesque approved these changes

2022-10-03 14:19 UTC, carlh98 approved these changes

2022-10-03 14:21 UTC, merged