feat!: Target Uno 5
nventive/Chinook.DynamicMvvm pull request #96
Opened 2023-12-21 16:54 UTC by juliecantin

GitHub Issue: #

## Proposed Changes

 - [ ] Bug fix
 - [x] Feature
 - [ ] Code style update (formatting)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build or CI related changes
 - [ ] Documentation content changes
 - [ ] Other, please describe:

## What is the current behavior?
Chinook.DynamicMvvm targets Uno 4, .net 6 and supports Xamarin.

## What is the new behavior?
Chinook.DynamicMvvm targets Uno 5, .net 7 and doesn't support Xamarin.

## Impact on version

- [x] **Major** (Public API was modified.)
  - Public constructs (class, struct, delegate, enum, etc.) were removed or renamed.
  - Public members were removed or renamed.
  - Public method signatures were changed or renamed.
- [ ] **Minor** (Public API was extended.)
  - Public constructs, members, or overloads were added.
- [ ] **Patch** (Public API was unchanged.)
  - A bug in behavior was fixed.
  - Documentation was changed.
- [ ] **None** (The library is unchanged.)
  - Only code under the `build` folder was changed.
  - Only code under the `.github` folder was changed.

## Checklist

Please check that your PR fulfills the following requirements:

- [x] Documentation has been added/updated.
- [ ] Automated Unit / Integration tests for the changes have been added/updated.
- [x] Updated [BREAKING_CHANGES.md](../BREAKING_CHANGES.md) (if you introduced a breaking change).
- [x] Your conventional commits are aligned with the **Impact on version** section.

Apps need to [migrate to Uno 5](https://platform.uno/docs/articles/migrating-to-uno-5.html).

## Other information

2023-12-21 18:12 UTC, jeanplevesque requested changes

2023-12-21 18:12 UTC, jeanplevesque commented on README.md
> +### Legacy
Use `####` instead of `###` because this should be under the Dispatcher header.

2023-12-21 18:12 UTC, jeanplevesque commented on src/DynamicMvvm.Uno.WinUI/DynamicMvvm.Uno.WinUI.csproj
> -	<PropertyGroup Condition="'$(TargetFramework)'=='netstandard2.0'">
Keep WASM support, use `net7.0`.

2023-12-22 17:53 UTC, jeanplevesque approved these changes

2023-12-22 18:09 UTC, carlh98 approved these changes

2023-12-22 18:09 UTC, merged